// ng/src/app/score/score.component.ts
import { ScoreService } from '../shared/score/score.service';
import { Component, OnInit } from '@angular/core';
import { faStar as farStar } from '@fortawesome/free-regular-svg-icons';
import { faStopwatch, faShoePrints, faStar as fasStar } from '@fortawesome/free-solid-svg-icons';
import { MissionScoreService } from '../mission-score.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-score',
  templateUrl: './score.component.html',
  styleUrls: ['./score.component.css']
})
export class ScoreComponent implements OnInit {
  faStopwatch = faStopwatch;
  faShoePrints = faShoePrints;
  farStar = farStar;
  fasStar = fasStar;

  time: number;
  steps: number;
  compliment: string;

  constructor(
    private _missionScoreService: MissionScoreService,
    private _scoreService: ScoreService,
    private _router: Router
  ) { }

  ngOnInit() {
    this.time = this._missionScoreService.time;
    this.steps = this._missionScoreService.steps;

    let level = this._missionScoreService.level;
    if (level !== undefined) {
      level++;
      this._missionScoreService.level = level;
    }
  }

  get stars(): number[] {
    const boundary = this._missionScoreService.answer;
    let score = Math.floor((boundary / this.steps) * 5);
    if (score > 5) {
      score = 5;
    }
    if (score < 1) {
      score = 1;
    }
    const stars = [];
    for (let i = 0; i < score; i++) {
      stars.push(1);
    }

    switch (score) {
      case 5:
        this.compliment = 'Excellent!';
        break;
      case 4:
        this.compliment = 'Great!';
        break;
      case 3:
        this.compliment = 'Nice';
        break;
      case 2:
        this.compliment = 'Good';
        break;
      case 1:
        this.compliment = 'Fine';
        break;
      default:
        this.compliment = '';
        break;
    }
    return stars;
  }

  onSubmit() {
    let name = localStorage.getItem('player');
    if (name === null) {
      name = '';
    }
    do {
      name = prompt('Player Name:');
    } while (name === '');
    if (name == null) {
      return;
    }
    localStorage.setItem('player', name);
    const level = this._missionScoreService.level;
    if (level === undefined || this.time === undefined || this.steps === undefined) {
      return;
    }
    this._scoreService.submit.score(name, level, Math.floor(this.time / 1000), this.steps)
      .subscribe((success) => {
        if (success === true) {
          this._router.navigate(['/ranking']);
        }
      });
  }

  onContinue() {
    let level = this._missionScoreService.level;
    if (level === undefined) {
      level = 1;
    }
    this._router.navigate(['/mission', level]);
  }
}

// vue/src/components/Score.vue
<template>
  <div :class="['splash-wrapper', 'flex-column', visibility]">
    <div class="score flex-column">
      <div class="header"><h1>Player Score</h1></div>
      <div class="score-group">
        <h1><i class="fa fa-stopwatch"></i></h1>
        <h2>Time</h2>
        <h2>{{duration}}</h2>
      </div>
      <div class="score-group">
        <h1><i class="fa fa-shoe-prints"></i></h1>
        <h2>Steps</h2>
        <h2>{{steps}}</h2>
      </div>
      <div class="score-group">
        <h1><i class="fa fa-star" v-for="(star, i) in stars" :key="i"></i></h1>
        <h2>{{compliment}}</h2>
      </div>
    </div>
    <div class="navigate flex-column fixed-position">
      <button class="btn btn-submit" @click="onSubmit">Submit Score</button>
      <button class="btn btn-continue" @click="onContinue">Next Mission</button>
    </div>
  </div>
</template>

<script>
import { formatTimer } from '../lib/timer';
import * as enigmaApi from '../lib/enigma.api';
export default {
  name: 'score',
  props: {
    level: Number,
    time: Number,
    steps: Number,
    answer: Number,
    splash: String
  },
  computed: {
    visibility() {
      return this.splash === '_score' ? '' : 'hidden';
    },
    duration() {
      return formatTimer(this.time);
    },
    score() {
      let score = Math.floor((this.answer / this.steps) * 5);
      return Math.max(1, Math.min(score, 5));
    },
    stars() {
      return Array.from({length: this.score}).fill(1)
    },
    compliment() {
      const compliment = {
        5: 'Excellent!',
        4: 'Great!',
        3: 'Nice',
        2: 'Good',
        1: 'Fine'
      }
      return compliment[this.score];
    }
  },
  methods: {
    onSubmit() {
      let name = localStorage.getItem('player');
      do {
        name = prompt('Player Name:').trim();
      } while (!name);
      localStorage.setItem('player', name);
      if (!this.level || !this.time || ! this.steps) return;
      enigmaApi
        .submitScore(name, this.level, Math.floor(this.time / 1000), this.steps)
        .then(success => {
          if (success) {
            this.$emit('rank');
          }
        });
    },
    onContinue() {
      this.$emit('nextmission');
    }
  }
}
</script>

<style>
@import '../styles/score.css';
@import '../styles/navigate.css';
</style>
